version: '2'

services:
  mysqldb:
   container_name: mysql_ucc
   build: ./database 
   ports:
    - "3307:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=test
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=ucc
    - MYSQL_ROOT_HOST=52.172.13.43
  
  frontend:
    image: ucc-frontend
    build: ./ui 
    links:
      - "backend:backend"
    depends_on: 
      - backend
    ports:
      - "4100:4100"

  backend:
    image: ucc-backend
    build: ./backend
    links:
      - "mysqldb:mysqldb"
    depends_on: 
      - mysqldb
    ports:
      - "3333:3333"
  
  