version: '2'

services:
  mysql:
   image: mysql:5.7
   container_name: mysql-health
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=test
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=googlefit